// -----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version: v4.0.30319
//   Service Registry Version: 3.23.0.0
//   Part of release: ${PackageName}
//   Generated at: ${GenerationDate}
//
//   Changes to this file may cause incorrect behaviour and
//   will be lost if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

define(["knockout", "models/oTH_PAYROLL_EVENT_CHILD"], function (ko, VM) {
  "use strict";

  var vm = new VM();

  vm.coreProcessingTransactionId = 1234567890123;
  vm.coreProcessingTransactionTypeCode = 10;
  vm.coreProcessingTransactionStatusCode = 165;

  vm.coreProcessingTransactionLastUpdatedById = "UBRMQ";
  vm.coreProcessingTransactionLastUpdatedDate = "2019-01-17";
  vm.coreProcessingTransactionLastUpdatedSourceCode = 5;
  vm.coreProcessingTransactionLastUpdatedReasonCode = 10;

  vm.clientInternalId = 3210987654321;
  vm.clientAccountId = "123456789012";
  vm.clientRoleTypeCode = 5;
  vm.clientAccountSequenceNumber = 8;

  vm.fdfFormId = 10131;
  vm.formType = 95555;
  vm.formYear = 2019;
  vm.formMonthNumber = 6;
  vm.formPeriodBeginDate = "2018-07-01";
  vm.formPeriodEndDate = "2019-06-30";

  vm.formReceivedDate = "2019-07-08";
  vm.formCompletedDate = "2019-07-16";
  vm.formStatusCode = 110;
  vm.formBatchId = "abc";
  vm.channelTypeCode = "number 5";
  vm.caseId = "brief";

  vm.sourceCoreProcessingTransactionId = 2345678901234;
  vm.originalReturnCoreProcessingTransactionId = 3456789012345;
  vm.suspendedTransactionHeaderStatusCode = 15;

  vm.documentId = "foo";
  vm.documentTypeCode = 456;

  vm.processMessages = ko.observableArray();

  // OTH-PAYER_DTLS
  vm.oTH_PAYER_DTLS_ClientExternalID("claKMcc0w6RM");
  vm.oTH_PAYER_DTLS_ClientExternalIdentifierTypeCode("666");
  vm.oTH_PAYER_DTLS_UnstructuredFullName("1jyn14N2vLEoqXhJZE_vAZKZBpINdhfchSNk4FONEoeRhwe17Tkr7hLaZYlLuAXOqnHYJ9RU2wqW644QKTRK8yh_GyKeeCeERQm5pGr0BQ2J2zggfVAbuMR3FHRVxx1ySlFpR_mEmSIr9YJRSp0JCDVE0uzhzVMPaC2Pu2Pgu8zbDk6s0_DIyrwPQAqiLEPRG5R7h5ib");
  vm.oTH_PAYER_DTLS_DerivedClientIdentifierAustralianBusinessNumber("ZdaGO6BY1Gjz");
  vm.oTH_PAYER_DTLS_DerivedUnstructuredFullName("REcuQl_uKsVqriUKT0KEcntUQqAW_SsEfa_Cbhp85zQsHuZrk2E28fXpVHdllou4_RLRiSuwUOKnWANhQTwJN3H_CUrTEDVQEYt2jIJSGThtUuSV68VR3lpIJLONlasQ46j0SX9IKeC6UZqTBWZItEYetlrY57rrmQ1aLUCi0MGYjvyvf7LOBjiygFPsqjPPxWSDjQHs");
  vm.oTH_PAYER_DTLS_BusinessMangamentSoftwareIdentifier("U2Jh0_69x840udpCtB5GEV4Z93mNcuLPye6KaB1hKR6trRfTrQUhXBn00ujGXsgCwoKQifnsMX7xaJtrWTgMZo3x28LqcuJcw49CGPwLonVAF1i1A4vEMTnHwYZmU8QdNeBiLrkHhUixS3rBYVpj0EQdP1Qt2J3rW4xmzAoUToh3v215rXO0RreINjTWa2RYc3bZFEMY");
  vm.oTH_PAYER_DTLS_EmployerBranchCode("3907298");
  vm.oTH_PAYER_DTLS_DerivedClientBranchNumber("-3178603");

  // OTH-PAYEE_DTLS
  vm.oTH_PAYEE_DTLS_CurrentPayerPayeeRelationshipPayeePayrollIdentifier("QViZsYAWCd75apZpZQrS5dWJZ5aaznL1R8bIlz27VEzzcjbwAbq8rZcy0Y_y0liZSFneOQDkZw81ois2cpaY9OJ4fnJM1D8vhZhW89huXFh7cmJbrIVUKJcD8u_mH3vWzMTPBV6fHqA3sNb4etgrtnkX8daM07ngULGPT6ZVO2MfIlWtTGIZVEnMm7Ti7tgMDfhgHLjj");
  vm.oTH_PAYEE_DTLS_PayerPayeeRelationshipCommencementDate("6110-08-22");
  vm.oTH_PAYEE_DTLS_PayerPayeeRelationshipCessationDate("5723-11-19");
  vm.oTH_PAYEE_DTLS_ClientIdentifierTaxFileNumber("mwvgs8bO1oZ1");
  vm.oTH_PAYEE_DTLS_ContractorClientIdentifierAustralianBusinessNumber("UR0MhL0cv8ib");
  vm.oTH_PAYEE_DTLS_StructuredFamilyName("olTSFvUPIApxJHqpaMrqlmTw3ZlWlnapNU4GoJIE");
  vm.oTH_PAYEE_DTLS_StructuredGivenName("UKrUmLDafTBiQ32CRharK9ofkAj1PkARDnWa60Jq");
  vm.oTH_PAYEE_DTLS_StructuredOtherGivenName("WL3Rm4YVd2zGtc5WgMumnOK7TveogaITXvU_GX5s");
  vm.oTH_PAYEE_DTLS_IndividualBirthDate("7825-02-18");
  vm.oTH_PAYEE_DTLS_UnstructuredGeographicAddressLine1("t_5sOhDIA803Yv1Ctgt0H5QJTCAZ3wKZL46hga");
  vm.oTH_PAYEE_DTLS_UnstructuredGeographicAddressLine2("E2rM_JZCU2YTrOLleztvZMhpQOwkqg2SgSc4R7");
  vm.oTH_PAYEE_DTLS_StructuredGeographicAddressLocalityName("6GuQtKBjF7NlYFyvA3UC8vY1WyAFxYxSTj6mBIeWosI2WE");
  vm.oTH_PAYEE_DTLS_StructuredGeographicAddressStateCode("Hvf");
  vm.oTH_PAYEE_DTLS_StructuredGeographicAddressPostcode("vSljO0Jt666K");
  vm.oTH_PAYEE_DTLS_CountryCode("41");
  vm.oTH_PAYEE_DTLS_PayeeInternetEmailAddress("7RzLMu3Y9ZPmidSqPlBFLtFkv5GOjMs7brbxTkSBaNm1uiLbmP6Vvm9MMPaTonzvsTL2CfXpSAp0HQ2NspmURXL1uOkEJ_YyY2HaXVZH3PCu80F8YNl0BfdVIVHz6TgSn3lQIa2XQfcBUb4vJoq7ZZw4XxRBOkMjuuHFXzz0XNsgCcAsdWqRnk5NFs4VJ1JqT5SkTyXU");
  vm.oTH_PAYEE_DTLS_PayeeTelephoneNumber("zsjLsQ27xji3667K");

  // OTH-PAYROLL_EVNT
  vm.oTH_PAYROLL_EVNT_PayrollEventPeriodStartDate("4425-10-17");
  vm.oTH_PAYROLL_EVNT_PayrollEventPeriodEndDate("4110-01-10");
  vm.oTH_PAYROLL_EVNT_FinancialYear("9737");
  vm.oTH_PAYROLL_EVNT_LodgmentDate("0794-10-12");
  vm.oTH_PAYROLL_EVNT_PaymentDate("8262-06-03");
  vm.oTH_PAYROLL_EVNT_PayrollMessageTimestampSourceDatetime("IuYzsYV4AHqCsxWJ45jc_JIaJy");
  vm.oTH_PAYROLL_EVNT_PayrollEventFinalIndicator("Y");

  // OTH-WAGE_AND_TAX_ITEM
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeExemptAmount("-70796665436.2");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeIncomeCommunityDevelopmentEmploymentProjectAmount("-27969100228.78");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumACode("666");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumAAmount("84400864190.5");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumBAmount("-40533129316.26");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumDAmount("-51537280311.58");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumEAmount("-11318310236.69");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeYearToDateIncomeGrossAmount("63869761563.10");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeEmploymentGrossAmount("-53971525016.80");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeEmploymentJointPetroleumDevelopmentAreaGrossAmount("-12149437925.16");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeIncomeLabourHireArrangementGrossAmount("18363499107.41");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeIncomeVoluntaryAgreementGrossAmount("-90645292722.49");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeIncomeOtherAmount("-63479278992.20");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeIncomeWorkingHolidayMakerYearToDateGrossAmount("-13867268281.56");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeFringeBenefitsReportableTaxableAmount("-65585249488.15");
  vm.oTH_WAGE_AND_TAX_ITEM_PayeeFringeBenefitsReportableExemptAmount("-22213266944.35");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingYearToDateWithheldAmount("-50341955649.39");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingForeignEmploymentIncomeTotalAmount("3914637565.25");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingForeignEmploymentIncomeJointPetroleumDevelopmentAreaTotalAmount("88775483942.95");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingLabourHireTotalAmount("73730126747.27");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingVoluntaryAgreementTotalAmount("95517150229.3");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingOtherSpecifiedTotalAmount("-28640849961.77");
  vm.oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingWorkingHolidayMakerYearToDateTotalAmount("-13769556087.4");
  vm.oTH_WAGE_AND_TAX_ITEM_YearToDateForeignIncomeEmploymentTaxCreditWithheldAmount("-98654245191.4");
  vm.oTH_WAGE_AND_TAX_ITEM_JointPetroleumDevelopmentAreaForeignIncomeEmploymentTaxPaidYearToDateAmount("63773672946.89");
  vm.oTH_WAGE_AND_TAX_ITEM_PaymentSummaryTotalGrossPaymentAmount("-23630443604.69");
  vm.oTH_WAGE_AND_TAX_ITEM_TaxWithheldTotalAmount("19557644409.74");
  vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5s([
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    ),
    new vm.oTH_WAGE_AND_TAX_ITEM_SectionGroup5(
      "666",
      "9390-06-09",
      "91694575547.63",
      "63965815731.4",
      "-99119288764.65"
    )
  ]);

  // OTH-DEDUCTION_ITEM
  vm.oTH_DEDUCTION_ITEM_SectionGroup3s([
    new vm.oTH_DEDUCTION_ITEM_SectionGroup3(
      "666",
      "56619403130.11"
    ),
    new vm.oTH_DEDUCTION_ITEM_SectionGroup3(
      "666",
      "56619403130.11"
    )
  ]);

  // OTH-ALLOWANCE_ITEM
  vm.oTH_ALLOWANCE_ITEM_AllowanceIncomeTotalAmount("12313994083.6");
  vm.oTH_ALLOWANCE_ITEM_SectionGroup4s([
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    ),
    new vm.oTH_ALLOWANCE_ITEM_SectionGroup4(
      "666",
      "djisit6i9RJJb76Axprq8NpeCqqSAF9_ymuUiH8R",
      "51745478818.53"
    )
  ]);

  // OTH-SUPER_ENTITLEMENT
  vm.oTH_SUPER_ENTITLEMENT_YearToDateSuperannuationGuaranteeEmployerContributionAmount("-61455597593.34");
  vm.oTH_SUPER_ENTITLEMENT_YearToDateSuperannuationGuaranteeOrdinaryTimeEarningsAmount("-76988234096.39");
  vm.oTH_SUPER_ENTITLEMENT_EmployerSuperannuationContributionReportableAmount("-13952294139.35");

  // OTH-TFN_DECLARATION
  vm.oTH_TFN_DECLARATION_PayerPayeeRelationshipPaymentBasisCode("666");
  vm.oTH_TFN_DECLARATION_PayeeClientResidentStatusCode("666");
  vm.oTH_TFN_DECLARATION_PayerPayeeRelationshipTaxFreeThresholdClaimedIndicator("Y");
  vm.oTH_TFN_DECLARATION_PayerPayeeRelationshipStudyandTrainingLoanRepaymentClaimedIndicator("Y");
  vm.oTH_TFN_DECLARATION_PayerPayeeRelationshipStudentFinancialSupplementDebtClaimedIndicator("Y");
  vm.oTH_TFN_DECLARATION_PayeeDeclarationIndicator("N");
  vm.oTH_TFN_DECLARATION_PayeeDeclarationDate("3175-04-26");
  vm.oTH_TFN_DECLARATION_PayerPayeeRelationshipTerminatedIndicator("N");

  return vm;
});
