function define() { module.exports = require("../../dependenciesMap").apply(this, arguments); }
// -----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version: v4.0.30319
//   Service Registry Version: 3.23.0.0
//   Part of release: ${PackageName}
//   Generated at: ${GenerationDate}
//
//   Changes to this file may cause incorrect behaviour and
//   will be lost if the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

define(function () {
  "use strict";

  return {
    oTH_PAYROLL_EVENT_CHILD: {
      sections: {
        10931: "Payer Details",
        10932: "Payee Details",
        10955: "Payee Details",
        10933: "Payroll Event",
        10936: "Wage And Taxation Item",
        10939: "Deduction Item",
        10941: "Allowance Item",
        10943: "Super Entitlement",
        11303: "TFN Declaration",
        60088: "TFN Declaration",
        10958: "TFN Declaration",
        11306: "TFN Declaration",
        10956: "TFN Declaration",
        11120: "TFN Declaration",
        11121: "TFN Declaration",
        11122: "TFN Declaration",
        11629: "TFN Declaration",
        11940: "TFN Declaration",
        12916: "TFN Declaration",
        11123: "TFN Declaration",
        11124: "TFN Declaration",
        11125: "TFN Declaration",
        11126: "TFN Declaration",
        11630: "TFN Declaration",
        11941: "TFN Declaration",
        11127: "TFN Declaration",
        11128: "TFN Declaration"
      },

      fields: [
        [ 10931, 16556, "", "oTH_PAYER_DTLS_ClientExternalID" ],
        [ 10931, 14930, "", "oTH_PAYER_DTLS_ClientExternalIdentifierTypeCode" ],
        [ 10931, 16557, "", "oTH_PAYER_DTLS_UnstructuredFullName" ],
        [ 10931, 23930, "", "oTH_PAYER_DTLS_DerivedClientIdentifierAustralianBusinessNumber" ],
        [ 10931, 23951, "", "oTH_PAYER_DTLS_DerivedUnstructuredFullName" ],
        [ 10931, 15431, "", "oTH_PAYER_DTLS_BusinessMangamentSoftwareIdentifier" ],
        [ 10931, 18449, "", "oTH_PAYER_DTLS_EmployerBranchCode" ],
        [ 10931, 20472, "", "oTH_PAYER_DTLS_DerivedClientBranchNumber" ],

        [ 10932, 16558, "", "oTH_PAYEE_DTLS_CurrentPayerPayeeRelationshipPayeePayrollIdentifier" ],
        [ 10932, 25443, "", "oTH_PAYEE_DTLS_PayerPayeeRelationshipCommencementDate" ],
        [ 10932, 25242, "", "oTH_PAYEE_DTLS_PayerPayeeRelationshipCessationDate" ],
        [ 10932, 16560, "", "oTH_PAYEE_DTLS_ClientIdentifierTaxFileNumber" ],
        [ 10932, 25444, "", "oTH_PAYEE_DTLS_ContractorClientIdentifierAustralianBusinessNumber" ],
        [ 10932, 16561, "", "oTH_PAYEE_DTLS_StructuredFamilyName" ],
        [ 10932, 16562, "", "oTH_PAYEE_DTLS_StructuredGivenName" ],
        [ 10932, 16565, "", "oTH_PAYEE_DTLS_StructuredOtherGivenName" ],
        [ 10932, 25445, "", "oTH_PAYEE_DTLS_IndividualBirthDate" ],
        [ 10932, 16567, "", "oTH_PAYEE_DTLS_UnstructuredGeographicAddressLine1" ],
        [ 10932, 16568, "", "oTH_PAYEE_DTLS_UnstructuredGeographicAddressLine2" ],
        [ 10932, 16571, "", "oTH_PAYEE_DTLS_StructuredGeographicAddressLocalityName" ],
        [ 10932, 16572, "", "oTH_PAYEE_DTLS_StructuredGeographicAddressStateCode" ],
        [ 10932, 16573, "", "oTH_PAYEE_DTLS_StructuredGeographicAddressPostcode" ],
        [ 10932, 16574, "", "oTH_PAYEE_DTLS_CountryCode" ],
        [ 10932, 25446, "", "oTH_PAYEE_DTLS_PayeeInternetEmailAddress" ],
        [ 10932, 25447, "", "oTH_PAYEE_DTLS_PayeeTelephoneNumber" ],

        [ 10933, 16580, "", "oTH_PAYROLL_EVNT_PayrollEventPeriodStartDate" ],
        [ 10933, 16582, "", "oTH_PAYROLL_EVNT_PayrollEventPeriodEndDate" ],
        [ 10933, 18450, "", "oTH_PAYROLL_EVNT_FinancialYear" ],
        [ 10933, 16585, "", "oTH_PAYROLL_EVNT_LodgmentDate" ],
        [ 10933, 16710, "", "oTH_PAYROLL_EVNT_PaymentDate" ],
        [ 10933, 25451, "", "oTH_PAYROLL_EVNT_PayrollMessageTimestampSourceDatetime" ],
        [ 10933, 25452, "", "oTH_PAYROLL_EVNT_PayrollEventFinalIndicator" ],

        [ 10936, 15470, "", "oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeExemptAmount" ],
        [ 10936, 15488, "", "oTH_WAGE_AND_TAX_ITEM_PayeeIncomeCommunityDevelopmentEmploymentProjectAmount" ],
        [ 10936, 15453, "oTH_WAGE_AND_TAX_ITEM_SectionGroup5", "oTH_WAGE_AND_TAX_ITEM_EmploymentTerminationPaymentTypeCode" ],
        [ 10936, 25453, "oTH_WAGE_AND_TAX_ITEM_SectionGroup5", "oTH_WAGE_AND_TAX_ITEM_EmploymentTerminationPaymentPaymentDate" ],
        [ 10936, 25454, "oTH_WAGE_AND_TAX_ITEM_SectionGroup5", "oTH_WAGE_AND_TAX_ITEM_EmploymentTerminationPaymentTaxWithheldTotalAmount" ],
        [ 10936, 15489, "oTH_WAGE_AND_TAX_ITEM_SectionGroup5", "oTH_WAGE_AND_TAX_ITEM_EmploymentTerminationPaymentTaxFreeAmount" ],
        [ 10936, 15496, "oTH_WAGE_AND_TAX_ITEM_SectionGroup5", "oTH_WAGE_AND_TAX_ITEM_EmploymentTerminationPaymentTaxableComponentAmount" ],
        [ 10936, 16787, "", "oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumACode" ],
        [ 10936, 15499, "", "oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumAAmount" ],
        [ 10936, 15501, "", "oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumBAmount" ],
        [ 10936, 15508, "", "oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumDAmount" ],
        [ 10936, 15510, "", "oTH_WAGE_AND_TAX_ITEM_PayeeAnnualLongServiceLeaveUnusedLumpSumEAmount" ],
        [ 10936, 15454, "", "oTH_WAGE_AND_TAX_ITEM_PayeeYearToDateIncomeGrossAmount" ],
        [ 10936, 25455, "", "oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeEmploymentGrossAmount" ],
        [ 10936, 25456, "", "oTH_WAGE_AND_TAX_ITEM_PayeeForeignIncomeEmploymentJointPetroleumDevelopmentAreaGrossAmount" ],
        [ 10936, 15456, "", "oTH_WAGE_AND_TAX_ITEM_PayeeIncomeLabourHireArrangementGrossAmount" ],
        [ 10936, 15518, "", "oTH_WAGE_AND_TAX_ITEM_PayeeIncomeVoluntaryAgreementGrossAmount" ],
        [ 10936, 25457, "", "oTH_WAGE_AND_TAX_ITEM_PayeeIncomeOtherAmount" ],
        [ 10936, 27454, "", "oTH_WAGE_AND_TAX_ITEM_PayeeIncomeWorkingHolidayMakerYearToDateGrossAmount" ],
        [ 10936, 25458, "", "oTH_WAGE_AND_TAX_ITEM_PayeeFringeBenefitsReportableTaxableAmount" ],
        [ 10936, 25459, "", "oTH_WAGE_AND_TAX_ITEM_PayeeFringeBenefitsReportableExemptAmount" ],
        [ 10936, 16820, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingYearToDateWithheldAmount" ],
        [ 10936, 25460, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingForeignEmploymentIncomeTotalAmount" ],
        [ 10936, 25461, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingForeignEmploymentIncomeJointPetroleumDevelopmentAreaTotalAmount" ],
        [ 10936, 25462, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingLabourHireTotalAmount" ],
        [ 10936, 25463, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingVoluntaryAgreementTotalAmount" ],
        [ 10936, 25464, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingOtherSpecifiedTotalAmount" ],
        [ 10936, 27455, "", "oTH_WAGE_AND_TAX_ITEM_PayAsYouGoWithholdingWorkingHolidayMakerYearToDateTotalAmount" ],
        [ 10936, 15523, "", "oTH_WAGE_AND_TAX_ITEM_YearToDateForeignIncomeEmploymentTaxCreditWithheldAmount" ],
        [ 10936, 27456, "", "oTH_WAGE_AND_TAX_ITEM_JointPetroleumDevelopmentAreaForeignIncomeEmploymentTaxPaidYearToDateAmount" ],
        [ 10936, 26716, "", "oTH_WAGE_AND_TAX_ITEM_PaymentSummaryTotalGrossPaymentAmount" ],
        [ 10936, 26717, "", "oTH_WAGE_AND_TAX_ITEM_TaxWithheldTotalAmount" ],

        [ 10939, 16825, "oTH_DEDUCTION_ITEM_SectionGroup3", "oTH_DEDUCTION_ITEM_IndividualDeductionTypeCode" ],
        [ 10939, 16833, "oTH_DEDUCTION_ITEM_SectionGroup3", "oTH_DEDUCTION_ITEM_IndividualDeductionYearToDateAmount" ],

        [ 10941, 16835, "oTH_ALLOWANCE_ITEM_SectionGroup4", "oTH_ALLOWANCE_ITEM_AllowanceIncomeTypeCode" ],
        [ 10941, 15524, "oTH_ALLOWANCE_ITEM_SectionGroup4", "oTH_ALLOWANCE_ITEM_AllowanceIncomeTypeOtherDescriptionText" ],
        [ 10941, 16841, "oTH_ALLOWANCE_ITEM_SectionGroup4", "oTH_ALLOWANCE_ITEM_AllowanceIncomeYearToDateAmount" ],
        [ 10941, 25465, "", "oTH_ALLOWANCE_ITEM_AllowanceIncomeTotalAmount" ],

        [ 10943, 15525, "", "oTH_SUPER_ENTITLEMENT_YearToDateSuperannuationGuaranteeEmployerContributionAmount" ],
        [ 10943, 15521, "", "oTH_SUPER_ENTITLEMENT_YearToDateSuperannuationGuaranteeOrdinaryTimeEarningsAmount" ],
        [ 10943, 25466, "", "oTH_SUPER_ENTITLEMENT_EmployerSuperannuationContributionReportableAmount" ],

        [ 11303, 25467, "", "oTH_TFN_DECLARATION_PayerPayeeRelationshipPaymentBasisCode" ],
        [ 11303, 25468, "", "oTH_TFN_DECLARATION_PayeeClientResidentStatusCode" ],
        [ 11303, 25469, "", "oTH_TFN_DECLARATION_PayerPayeeRelationshipTaxFreeThresholdClaimedIndicator" ],
        [ 11303, 28130, "", "oTH_TFN_DECLARATION_PayerPayeeRelationshipStudyandTrainingLoanRepaymentClaimedIndicator" ],
        [ 11303, 25476, "", "oTH_TFN_DECLARATION_PayerPayeeRelationshipStudentFinancialSupplementDebtClaimedIndicator" ],
        [ 11303, 25478, "", "oTH_TFN_DECLARATION_PayeeDeclarationIndicator" ],
        [ 11303, 25479, "", "oTH_TFN_DECLARATION_PayeeDeclarationDate" ],
        [ 11303, 28352, "", "oTH_TFN_DECLARATION_PayerPayeeRelationshipTerminatedIndicator" ]
      ]
    }
  };
});
